export const ENGINE_ENV_KEYS = {
  convexUrl: "CONVEX_URL",
  redisUrl: "REDIS_URL",
  redisHost: "REDISHOST",
  redisPort: "REDISPORT",
  redisUser: "REDISUSER",
  redisPassword: "REDISPASSWORD",
  redisKeyPrefix: "REDIS_KEY_PREFIX",
  temporalAddress: "TEMPORAL_ADDRESS",
  temporalNamespace: "TEMPORAL_NAMESPACE",
  temporalTlsEnabled: "TEMPORAL_TLS_ENABLED",
  temporalTlsServerName: "TEMPORAL_TLS_SERVER_NAME",
  temporalRetryDelayMs: "TEMPORAL_RETRY_DELAY_MS",
  temporalRunTaskQueue: "TEMPORAL_RUN_TASK_QUEUE",
  temporalWindowTaskQueue: "TEMPORAL_WINDOW_TASK_QUEUE",
  temporalTestServerMode: "TEMPORAL_TEST_SERVER_MODE",
  temporalTestServerDownloadDir: "TEMPORAL_TEST_SERVER_DOWNLOAD_DIR",
  temporalTestServerExecutable: "TEMPORAL_TEST_SERVER_EXECUTABLE",
  openaiApiKey: "OPENAI_API_KEY",
  anthropicApiKey: "ANTHROPIC_API_KEY",
  googleGenerativeAiApiKey: "GOOGLE_GENERATIVE_AI_API_KEY",
  firecrawlApiKey: "FIRECRAWL_API_KEY",
  axiomDataset: "AXIOM_DATASET",
  axiomToken: "AXIOM_TOKEN",
} as const;
